apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.app }}-certificate"
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.tlsSecretName }}
  dnsNames:
    - {{ .Values.hostname }}
  issuerRef:
    kind: {{ .Values.issuer.kind }}
    name: {{ .Values.issuer.name }}
  commonName: {{ .Values.hostname }}